### ISSUE TITLE
Equals sign from the query filter is dropped

### ISSUE THREAD

**Issue by blokhin** [sveltetools/svelte-pathfinder#10]
see https://github.com/tilde-lab/optimade.science/issues/13

**Comment by blokhin** [comment]
@PaulMaly ping?

**Comment by PaulMaly** [comment]
Yep, it’s look like an issue. I think we should investigate it and dix in the next release. Thanks for the report!

**Comment by PaulMaly** [comment]
Fixed in 3.0.0
