### ISSUE TITLE
Question: what is the preferred way to remove a query parameter?

### ISSUE THREAD

**Issue by red-meadow** [sveltetools/svelte-pathfinder#14]
I do this:

```javascript
delete $query.params.x
$query.params = $query.params
```

Perhaps there is a better way?

**Comment by PaulMaly** [comment]
I think it's general behavior for all svelte stores contained an object/array. if you meet this too often, I think make sense to write some kind of helper function for a more convenient usage:

```javascript
function delProp(store, prop) {
     store.update($store => {
         delete $store[prop];
         return $store;
     });
}
```

or you can wrap query `store` to your own and extend its functionality:

```javascript

export const myQuery = {
   ...query,
   del(param) {
      query.update(($query) => {
           delete $query.params[param];
           return $query;
      });
   }
};
...

myQuery.del('x');
```

Basically, `svelte-pathfinder` doesn't provide any additional API for svelte standard stores.
