### ISSUE TITLE
SSR support examples

### ISSUE THREAD

**Issue by tonyrewin** [sveltetools/svelte-pathfinder#19]
If there is any vision of how to do that - I'd like to know asap :)

**Comment by PaulMaly** [comment]
I still don't have understandable example of SSR support, because it's very depends on you server-side implementation. But basic example on `express` could looks like:

```javascript
require('svelte/register');
...
const App = require('./App.svelte').default;
...
app.get('*', (req, res) => {
  // register router hook
  require('svelte-pathfinder/ssr');
  
  // navigate router to current server URL
  goto(req.url); 
  
  // render an App with current state
  res.render('index', App.render(/* some data */)); 
});
```

But I definitely advise everybody to use `sveltekit` if you need to take universal approach in your apps.
