### ISSUE TITLE
Avoid empty query values

### ISSUE THREAD

**Issue by zyxd** [sveltetools/svelte-pathfinder#3]
To avoid url like /path?page=&search= maybe better to check a value is not empty?
Or maybe it is better to add an option to 'clean' the query.

https://github.com/PaulMaly/svelte-pathfinder/blob/39aa6c177ebaade5d093501b715d9e8ef917a111/src/helpers.js#L52

**Comment by PaulMaly** [comment]
Returned to this proposal. I wonder, how we should figure out which value is not acceptable to the query param and which is not? For example, we've got a query state like this:

```js
$query = {
   search: '',
   checked: false,
   selected: []
};
```
Should we remove the `search` param from this state? Is `checked` have a proper value at this moment? Seems both are falsy.

One more disadvantage is if we remove param from $query store we'll have to check all places to `undefined`. If we won't remove param from the store and just skip it in URL it will become some kind of inconsistency between state and URL. This inconsistency may cause us not to be able to recover falsy state for the specific value after page reload.

**Comment by zyxd** [comment]
Maybe it makes sense not to remove any parameters from the state object, but hide it from string before history.pushState?

**Comment by PaulMaly** [comment]
@zyxd The main issue is how to retrieve this state after page reload. So, this is exactly what I mean, our state is out of sync.

**Comment by zyxd** [comment]
@PaulMaly I think it should be optional and disabled by default. But how much will we lose if we don't keep null / undefined / '' values after page reload?

**Comment by PaulMaly** [comment]
@zyxd Seems, this will cause us to lose information about the parameter type and be forced to check the value for existence in all places we use it:

```
{#if $query.filters} <!-- this check become necesery -->
   {#each $query.filters as filter}
       ...
   {/each}
{/if}
```

**Comment by PaulMaly** [comment]
No updates here. Closed for now. Feel fee to open again if needed.
