### ISSUE TITLE
Possible to preserve paths on page refresh?

### ISSUE THREAD

**Issue by jonathanstegall** [sveltetools/svelte-pathfinder#33]
I'm noticing that whether I use `prefs.hashbang = true;` or not, when I'm on a route that isn't the root and I refresh the page, places where I use `$pattern` have become empty. Is there any way to make this persistent?

**Comment by PaulMaly** [comment]
Hi! Not sure I fully understand the case. Could you please give some code snippets or steps to reproduce this issue? Thanks!
