### ISSUE TITLE
Linking to path with query parameter triggers two history changes

### ISSUE THREAD

**Issue by ctrepka** [sveltetools/svelte-pathfinder#40]
## Current Behavior

**From path "/"**
<a href={${path}?=${query}}>Link with Query</a>

**Then from "{path}"**
function back() results in url `/${path}`
pressing browser back button results in the same behavior

## Desired Behavior
<a href={${path}?=${query}}>Link with Query</a>
would result in one history change, back button would return to "/" not "{path}"

**Comment by PaulMaly** [comment]
Close because of long inactivity.
