### ISSUE TITLE
"unload" event is deprecated

### ISSUE THREAD

**Issue by vlucendo** [sveltetools/svelte-pathfinder#45]
Hello,

First off great work on the router, it's very handy and some of its features were impossible to find in others, love it!

Recently on a project checking the Lighthouse report, I noticed the score from "best practises" went from 100 to 78 because it detected some deprecated API usage. After a bit of digging I realized it was coming from `svelte-pathfinder` usage of the `unload` event, which seems outdated: https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event

Would it be possible to work around it somehow?
Cheers.

**Comment by dxpm** [comment]
Hi, yea, looks like we should remove support of unload event due to the fact that it is now depricated. Thanks!

**Comment by PaulMaly** [comment]
@vlucendo v4.8.0 released with this change.
